version: '3.9'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:13.3-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      TIME_ZONE: America/Bahia
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    logging:
      options:
        max-size: '10m'
        max-file: '3'

  api:
    container_name: api
    restart: always
    env_file:
      - .env
    image: node:lts-alpine
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: sh -c "yarn init-dev-db && yarn dev"
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'

  pgadim:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    logging:
      options:
        max-size: '10m'
        max-file: '3'
